apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-fsd-config
  namespace: hello-fsd
data:
  SPRING_PROFILES_ACTIVE: "docker"
  DB_HOST: "hello-fsd-postgres"
  DB_PORT: "5432"
  DB_NAME: "hellofsd"
  CORS_ALLOWED_ORIGINS: "http://hello-fsd.local"
