apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-fsd-backend
  namespace: hello-fsd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-fsd-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-fsd-frontend
  namespace: hello-fsd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-fsd-frontend
